extract_questions_task:
  description: >
    Parse the application form to extract and list all its questions.
  expected_output: >
    A list of all questions in the application.

simplify_questions_task:
  description: >
    Simplify each application question into smaller, actionable questions.
  expected_output: >
    A structured list of simplified questions for each original application question.

gather_user_responses_task:
  description: >
    Present each simplified question to the user one at a time to collect their answers.
  expected_output: >
    A collection of user answers corresponding to the simplified questions.

generate_responses_task:
  description: >
    Use the collected user responses to generate well-crafted answers for the original application questions.
  expected_output: >
    A set of comprehensive and well-structured answers for the application questions.
